name: C/C++ CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: buildir
      run: mkdir build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make test
      run: make test
